project:
  type: website
  render:
    - "*.qmd"
    - "!*.md"
  resources:
    - "outputs/*"
    - "shared.css"

website:
  title: "DataScienceLab Movies"
  site-url: "https://cu-s26-msdssb-dsci-01-datasciencelab.github.io/DataScienceLab_Movies_1/"
  navbar:
    left:
      - text: "🏠 Home"
        href: index.qmd
  sidebar:
    style: "docked"
    contents:
      - text: "🏠 Home"
        href: index.qmd
      - text: "📊 Descriptive Analysis"
        href: sec1.qmd
      - text: "🤖 Machine Learning"
        href: sec2.qmd
      - text: "📝 Conclusion"
        href: conclusion.qmd
      - text: "📈 Dashboard"
        href: dashboard.qmd

format:
  html:
    theme: cosmo
    toc: false
    code-fold: true